<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SQLscripts\01-Tables.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SQLscripts\01-Tables.sql" />
    <EmbeddedResource Include="SQLscripts\03-SprocsForBusinessLogic.sql" />
    <EmbeddedResource Include="SQLscripts\02-SprocsForCrud.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Board.Common\Board.Common.csproj" />
  </ItemGroup>

</Project>
